name: NMR_env
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - pytorch
  - nvidia
dependencies:
  - ca-certificates
  - certifi
  - conda-forge::ffmpeg
  - conda-forge::openbabel
  - conda-forge::transformers
  - gh
  - jupyterlab
  - openssl
  - pip
  - pydantic
  - pytorch-cuda=12.1
  - rdkit
  - scikit-learn
  - seaborn
  - tensorboard
  - torchaudio
  - torchvision
  - pip:
      - antlr4-python3-runtime==4.9.3
      - h5py==3.12.1
      - hydra-core==1.3.2
      - lightning==2.4.0
      - lightning-utilities==0.11.9
      - omegaconf==2.3.0
      - pytorch-lightning==2.4.0
      - torchmetrics==1.6.0
